// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mchirico/go_test/configs/mocks (interfaces: Area)

// Package mockShapes is a generated GoMock package.
package mockShapes

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockArea is a mock of Area interface
type MockArea struct {
	ctrl     *gomock.Controller
	recorder *MockAreaMockRecorder
}

// MockAreaMockRecorder is the mock recorder for MockArea
type MockAreaMockRecorder struct {
	mock *MockArea
}

// NewMockArea creates a new mock instance
func NewMockArea(ctrl *gomock.Controller) *MockArea {
	mock := &MockArea{ctrl: ctrl}
	mock.recorder = &MockAreaMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockArea) EXPECT() *MockAreaMockRecorder {
	return m.recorder
}

// area mocks base method
func (m *MockArea) area() float64 {
	ret := m.ctrl.Call(m, "area")
	ret0, _ := ret[0].(float64)
	return ret0
}

// area indicates an expected call of area
func (mr *MockAreaMockRecorder) area() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "area", reflect.TypeOf((*MockArea)(nil).area))
}
